feature/emerald_components
cebroker/emerald-ios pull request #143
Opened 2022-01-18 22:22 UTC by ronalfabra

2022-01-19 13:58 UTC, RonaldRuizCondor requested changes

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormContainer.swift
> +    @State var isEditing: Bool
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    var minimumDate: Date?
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    var maximumDate: Date?
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getFormat() -> TextFormat {
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func fillYear(date: String?) -> String {
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getFormatDate(_ selectedDate: Date) -> String {
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getDate(from string: String) -> Date? {
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func formatText(_ text: String) -> String {
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
Delete white space

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
>      @State var selected: String?
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +    @State var itemPickerSelected: Int?
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +    @State(initialValue: "") var textV4: String
It should be private

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
Delete white specs

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
Delete white space

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
Delete white space

2022-01-19 13:58 UTC, RonaldRuizCondor commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +                    themeStyle: .primary) {
The closure should not be mandatory

2022-01-19 17:11 UTC, jmenco submitted a review, later dismissed

2022-01-19 21:40 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +                    themeStyle: .primary) {
this was developed in other sprint (other task), I don't modified this class for my scope.

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +    @State(initialValue: "") var textV4: String
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +    @State var itemPickerSelected: Int?
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
>      @State var selected: String?
done

2022-01-19 21:51 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
done

2022-01-19 21:51 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func formatText(_ text: String) -> String {
it was added in protocol, done.

2022-01-19 21:51 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getDate(from string: String) -> Date? {
it was added in protocol, done.

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getFormatDate(_ selectedDate: Date) -> String {
it was added in protocol, done.

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func fillYear(date: String?) -> String {
it was added in protocol, done.

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getFormat() -> TextFormat {
it was added in protocol, done.

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    var maximumDate: Date?
done

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    var minimumDate: Date?
done

2022-01-19 21:52 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormContainer.swift
> +    @State var isEditing: Bool
done

2022-01-19 21:54 UTC, ronalfabra commented on ProofOfConcept/ProofOfConcept/SwiftUi/SwiftUiView.swift
> +
done

2022-01-19 21:54 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func fillYear(date: String?) -> String {
it was added in protocol, done.

2022-01-19 21:55 UTC, ronalfabra commented on EmeraldIOS/Components/SwiftUi/TextField/TextFieldForm/EmeraldTextFieldFormDate/EmeraldTextFieldFormDateCoordinator.swift
> +    func getFormat() -> TextFormat {
it was added in protocol, done.

2022-01-19 22:27 UTC, RonaldRuizCondor approved these changes

2022-01-20 20:13 UTC, jmenco approved these changes

2022-01-20 20:23 UTC, merged